### PR TITLE
make it easy to install

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
This is to fix https://github.com/chef/fixie/issues/13

### CODE REVIEW

**Comment by jeremiahsnapp** [comment]
@manderson26 this is ready to be merged after your approval.

**Comment by jeremiahsnapp** [comment]
Until we release this to rubygems.org we'll still need to build the gem locally using the following command.

```
gem build ./fixie.gemspec
```

Then you can install the resultant fixie-0.1.0.gem into any Chef Server 12 and run it using the following commands.

```
/opt/opscode/embedded/bin/gem install ./fixie-0.1.0.gem --ignore-dependencies
/opt/opscode/embedded/bin/fixie
```

**Comment by manderson26** [comment]
Looks good to me. @paulmooring will this break how you deploy fixie in hosted? Otherwise I'm :+1: to merge.

**Comment by jeremiahsnapp** [comment]
@paulmooring I'd be happy to hear if this PR impacts deploying to hosted. This PR makes a move toward this being installed as an actual gem package rather than the current bundler way of installation. To finish the intended direction we still need to iron out details around how to push this to rubygems.org. For example, we may need to rename the gem since a fixie gem already exists in rubygems.org.

Once those details are solved and we push the gem to rubygems.org you can install this on a Chef Server by simply running the following command.

```
/opt/opscode/embedded/bin/gem install fixie --ignore-dependencies
```

You can install it on a remote management system (not a chef server) using the new PR on the fixie-scripts repo which includes a `fixie-cookbook`.

https://github.com/chef/fixie-scripts/pull/1

The intent there is to download the fixie-scripts repo to a remote management system that has Chef and Berkshelf or just ChefDK installed on it. Then just run the following commands to use the `fixie-cookbook` to install fixie (or whatever the new name is).

```
berks install
berks vendor cookbooks
chef-client -z -r fixie
cp fixie.conf.example fixie.conf
```

The `fixie-cookbook` uses `postgresql::ruby` to install the `pg` gem but it won't install correctly in ChefDK until this PR gets merged and released.

https://github.com/hw-cookbooks/postgresql/pull/283

I'm happy to take any input about all of this.

**Comment by manderson26** [comment]
One last question: is the install in getting started still correct? I think this changes that...
https://github.com/chef/fixie/blame/master/doc/GETTING_STARTED.md#L4

**Comment by jeremiahsnapp** [comment]
Yes the docs need to be changed but I wasn't sure if I should bother making that change yet since we don't have the gem in rubygems.org. If you want me to make docs changes now I can put instructions for how to build the gem locally. And then change them later when it's on rubygems.org.

**Comment by manderson26** [comment]
@jeremiahsnapp Let's merge this and add the docs for local gem building as a separate PR. @paulmooring seems ok with this change, and I'd like to get it in sooner rather than later.

**Pull request merged**
